version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.2.0
    restart: always
    depends_on:
      - postgres
      - requirements
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      # For encrypted connection passwords
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      # airflow access all dags from this location 
      - ../airflow/dags:/usr/local/airflow/dags
      - ./examples/intro-example/dags/python/requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  requirements:  # this will install the requirnments specified in requirnment.txt
      image: puckel/docker-airflow:1.10.1
      volumes:
      - ./examples/intro-example/dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
      command: bash -c pip install -r /requirements.txt

      
      # install nodejs after spawning instance.
      # install nodejs 
      # docker exec --user="root" -it f6e599caee53 /bin/bash
      # apt-get update -y
      # apt-get install nodejs 
      # The docker file is copied from (https://github.com/puckel/docker-airflow/blob/master/Dockerfile)
        
